stages:
  - build
  - test
  - deploy

image: alpine


build_a:
  stage: build
  tags:
    - asd
  script:
    - echo "JOjo creating file"
    - echo "hello jojo" > jojo.txt


test_a:
  stage: test
  tags:
    - asd
  dependencies:
    - build_a
  needs:
    - build_a
  variables:
    GIT_STRATEGY: none
  script: 
    - echo "Testing jojo"
    - ls
    - cat jojo.txt



deploy_a:
  stage: deploy
  tags:
    - asd
  needs:
    - test_a
  dependencies:
    - test_a
  script:
    - echo "Its ok jojo"
